---
- name: Enable Features
  tags: [vpc, vlans, trunks]
  loop:
    - vpc
    - lacp
  cisco.nxos.nxos_feature:
    feature: "{{ item }}"
    state: enabled

# BELOW LOOPS ARE COMMENTED OUT due to configuring 1 interface but should be altered when additional access switches are added 
- name: Create Port Channels for Access Switches
  tags: [ vpc, vlans, trunks]
#  loop: "{{ trunks }}"
  cisco.nxos.nxos_lag_interfaces:
    config: 
      - name: "port-channel{{ trunks.port_channel_id }}"
        members: 
          - member: "{{ trunks.members.0 }}"
            mode: active



- name: Make Port Channel Layer 2
  tags: [ vpc, vlans, trunks]
#  loop: "{{ trunks }}"
  cisco.nxos.nxos_interfaces:
    config: 
      - name: "port-channel{{ trunks.port_channel_id }}"
        description: "VPC PortChannel"
        enabled: true 
        mode: layer2 



- name: Configure Port Channel as Trunk
  tags: [ vpc, vlans, trunks]
#  loop: "{{ trunks }}"
  cisco.nxos.nxos_l2_interfaces:
    config:
      - name: "port-channel{{ trunks.port_channel_id }}"
        mode: trunk
        trunk: 
          native_vlan: 1
          allowed_vlans: 100,101,102,103



- name: Configure VPC for Trunks
  tags: [vpc, vlans, trunks]
#  loop: "{{ trunks }}"
  cisco.nxos.nxos_vpc_interface:
    portchannel: "{{ trunks.port_channel_id }}"
    vpc: "{{ vpc.domain }}"
