---
- name: Generate Access Layer Trunks and Etherchannel Configuration Files from Templates
  hosts: localhost
  gather_facts: false
  vars:
    config_dir: "{{ playbook_dir }}/configs"

  roles:
    - access_uplinks_jinja

- name: Deploy Access VLANS Config
  hosts: access
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Apply Config
      cisco.ios.ios_config:
        src: configs/{{ inventory_hostname }}-uplinks.conf