---
- name: Deploy Core with Jinja Templates
  hosts: 
    - core 
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Deploy Core Devices Configurations
      cisco.ios.ios_config:
        src: configs/{{ inventory_hostname }}.conf

- name: Deploy Distribution with Jinja Templates
  hosts: 
    - distribution
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Deploy Distribution Devices Configurations
      cisco.nxos.nxos_config:
        src: configs/{{ inventory_hostname }}.conf

- name: Deploy Access with Jinja Templates
  hosts: 
    - access 
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Deploy Access Devices Configurations
      cisco.nxos.nxos_config:
        src: configs/{{ inventory_hostname }}.conf
    
