---
- name: Generate Configuration Files from Templates
  hosts: localhost
  become: true
  gather_facts: false
  vars:
    config_dir: "{{ playbook_dir }}/configs"

  tasks:
    - name: Generate IOS Configuration Files
      loop: "{{ groups['core'] }}"
      vars:
        l3_interfaces: "{{ hostvars[item]['l3_interfaces'] }}"
      ansible.builtin.template:
        src: templates/core_config.j2
        dest: "{{ config_dir }}/{{ item }}.conf"


    # - name: Generate Distribution NXOS Configuration Files
    #   ansible.builtin.template:
    #     src: templates/dist_config.j2
    #     dest: "{{ config_dir }}/{{ item }}.conf"
    #   loop: "{{ groups['distribution'] }}"

    # - name: Generate Access NXOS Configuration Files
    #   ansible.builtin.template:
    #     src: templates/access_config.j2
    #     dest: "{{ config_dir }}/{{ item }}.conf"
    #   loop: "{{ groups['access'] }}"
