---
- name: Generate IOS OSPF Configuration Files from Templates
  hosts: localhost
  gather_facts: false
  vars:
    config_dir: "{{ playbook_dir }}/configs"

  roles:
    - ios_ospf_jinja

# - name: Deploy IOS OSPF Config
#   hosts: iosxe 
#   gather_facts: false
#   connection: network_cli

#   tasks:
#     - name: Apply Config
#       cisco.ios.ios_config:
#         src: configs/{{ inventory_hostname }}-ospf.conf