---
### Configure Core routers L3 interfaces and enable OSPF ###

- name: Configure IOS (core and access) L3 interfaces
  ansible.builtin.import_playbook: ios_l3_config.yml

- name: Configure IOS (core and access) OSPF
  ansible.builtin.import_playbook: ios_ospf_config.yml

### Configure Distribution L3 interfaces, OSPF, VPC, HSRP, and Trunks to access ###

- name: Configure Distribution Switches
  hosts: distribution 
  gather_facts: false
  connection: network_cli

  roles: 
    - nxos_vlans
    - nxos_vpc
    - nxos_vpc_trunks
    - nxos_l3_interfaces
    - nxos_hsrp
    - nxos_ospf

### Configure Access layer vlans, trunks, and loopback address ###

- name: Configure Access Switches VLANS
  ansible.builtin.import_playbook: access_vlans_config.yml
  
- name: Configure Access Switches Uplinks to DIST Port-Channel and Trunks
  ansible.builtin.import_playbook: access_uplinks_config.yml 

### Save Configs Block ###

- name: Save IOS Configs if modified
  hosts: iosxe
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Save IOS Running Config to Startup Config
      cisco.ios.ios_config:
        save_when: modified

- name: Save NXOS Configs if modified
  hosts: nxos
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Save NXOS Running Config to Startup Config
      cisco.nxos.nxos_config:
        save_when: modified

