---
# loops through the hosts in iosxe group and pulls in the host_vars array "ospf_networks" and "router_id" per host
- name: Generate IOS OSPF Configuration Files
  loop: "{{ groups['iosxe'] }}"
  vars:
    ospf_networks: "{{ hostvars[item]['ospf_networks'] }}"
    router_id: "{{ hostvars[item]['ospf_router_id'] }}"
  ansible.builtin.template:
    src: templates/ios_ospf.j2
    dest: "{{ config_dir }}/{{ item }}-ospf.conf"