---
- name: Generate IOS OSPF Configuration Files
  loop: "{{ groups['iosxe'] }}"
  vars:
    router_id: "{{ hostvars[item]['ospf_router_id'] }}"
    networks: "{{ hostvars[item]['ospf_networks'] }}"
  ansible.builtin.template:
    src: templates/ios_ospf.j2
    dest: "{{ config_dir }}/{{ item }}-ospf.conf"