---
- name: Configure OSPF Process and Router ID 
  tags: ospf 
  cisco.ios.ios_ospfv2:
    config:
      processes: 
        - router_id: "{{ ospf_router_id }}"
          process_id: "{{ ospf.process_id }}"


- name: Configure OSPF Interfaces
  tags: ospf
  loop: "{{ ospf.networks }}"
  cisco.ios.ios_ospf_interfaces:
    config:
      - name: "{{ item.interface }}"
        address_family:
          - afi: ipv4
            process:
              id: "{{ ospf.process_id }}"
              area_id: "{{ item.area }}"

  
