---
#- name: Enable Features
#  tags: [trunks, vlans]
#  loop:
#    - lacp
#  nxos_feature:
#    feature: "{{ item }}"
#    state: enabled
- name: Create uplink Port Channel to Distribution
  tags: [trunks, vlans]
  loop: "{{ uplinks }}"
  cisco.ios.ios_lag_interfaces:
    config:
      - name: "port-channel{{ item.port_channel_id }}"
        members:
          - member: "{{ item.members.0 }}"
            mode: active
          - member: "{{ item.members.1 }}"
            mode: active



- name: Make Port Channel layer 2
  tags: [trunks, vlans]
  loop: "{{ uplinks }}"
  cisco.ios.ios_interfaces:
    config:
      - name: "port-channel{{ item.port_channel_id }}"
        enabled: true
        mode: layer2



- name: Configure Port Channel as Trunk
  tags: [trunks, vlans]
  loop: "{{ uplinks }}"
  cisco.nxos.nxos_l2_interfaces:
    config:
      - name: "port-channel{{ item.port_channel_id }}"
        mode: "{{ item.mode }}"
        trunk:
          native-vlan: 1
        encapsulation: dot1q

#- name: Create uplink Port Channel to Distribution
#  tags: [trunks, vlans]
#  loop: "{{ uplinks }}"
#  cisco.nxos.nxos_lag_interfaces:
#    config:
#      - name: "port-channel{{ item.port_channel_id }}"
#        members:
#          - member: "{{ item.members.0 }}"
#            mode: active
#          - member: "{{ item.members.1 }}"
#            mode: active
#
#
#
#- name: Make Port Channel layer 2
#  tags: [trunks, vlans]
#  loop: "{{ uplinks }}"
#  cisco.nxos.nxos_interfaces:
#    config:
#      - name: "port-channel{{ item.port_channel_id }}"
#        enabled: true
#        mode: layer2
#
#
#
#- name: Configure Port Channel as Trunk
#  tags: [trunks, vlans]
#  loop: "{{ uplinks }}"
#  cisco.nxos.nxos_l2_interfaces:
#    config:
#      - name: "port-channel{{ item.port_channel_id }}"
#        trunk:
#          native-vlan: 1
#          allowed-vlans: 100,101,102,103


    