---
l3_interfaces:
  - interface_type: Loopback
    interface_id: 0
    description: Default Loopback
    ip_address: 10.10.11.3
    netmask: 255.255.255.255
    prefix: 32
    area: 0
mgmt_interface: Ethernet0/3
ospf_router_id: 5.5.5.5
ospf_networks:
  - network: 10.10.11.3
    mask: 0.0.0.0
    area: 0
vlans:
  - id: 100
    name: VLAN100
    gateway: 172.16.100.1
  - id: 101
    name: VLAN101
    gateway: 172.16.101.1
  - id: 102
    name: VLAN102
    gateway: 172.16.102.1
  - id: 103
    name: VLAN103
    gateway: 172.16.103.1
uplinks:
  port_channel_id: 1
  members:
    - Ethernet0/0
    - Ethernet0/1
  mode: trunk
  encapsulation: dot1q