---
l3_interfaces:
  - interface_type: Ethernet
    interface_id: 0/0
    description: L3 Link to DIST-2
    ip_address: 172.16.0.13
    netmask: 255.255.255.252
    prefix: 30
  - interface_type: Ethernet
    interface_id: 0/1
    description: L3 Link to DIST-1
    ip_address: 172.16.0.9
    netmask: 255.255.255.252
    prefix: 30
  - interface_type: Ethernet
    interface_id: 0/2
    description: L3 Link to CORE-1
    ip_address: 172.16.0.18
    netmask: 255.255.255.252
    prefix: 30
  - interface_type: Loopback
    interface_id: 0
    description: Default Loopback
    ip_address: 10.10.10.2
    netmask: 255.255.255.255
    prefix: 32
mgmt_interface: Ethernet0/3
ospf_router_id: 2.2.2.2
ospf_networks:
    - network: 172.16.0.8
      mask: 0.0.0.3
      area: 0
    - network: 172.16.0.12
      mask: 0.0.0.3
      area: 0
    - network: 172.16.0.16
      mask: 0.0.0.3
      area: 0
    - network: 10.10.10.2
      mask: 0.0.0.0
      area: 0
