---
l3_interfaces:
  - interface_type: Ethernet
    interface_id: 0/0
    description: L3 Link to DIST-1
    ip_address: 172.16.0.1
    netmask: 255.255.255.252
    prefix: 30
  - interface_type: Ethernet
    interface_id: 0/1
    description: L3 Link to DIST-2
    ip_address: 172.16.0.5
    netmask: 255.255.255.252
    prefix: 30
  - interface_type: Ethernet
    interface_id: 0/2
    description: L3 Link to CORE-2
    ip_address: 172.16.0.17
    netmask: 255.255.255.252
    prefix: 30
  - interface_type: Loopback
    interface_id: 0
    description: Default Loopback
    ip_address: 10.10.10.1
    netmask: 255.255.255.255
    prefix: 32
mgmt_interface: Ethernet0/3
ospf_router_id: 1.1.1.1
ospf_networks:
    - network: 172.16.0.0
      mask: 0.0.0.3
      area: 0
    - network: 172.16.0.4
      mask: 0.0.0.3
      area: 0
    - network: 172.16.0.16
      mask: 0.0.0.3
      area: 0
    - network: 10.10.10.1
      mask: 0.0.0.0
      area: 0