---
- name: Enable Features
  tags: hsrp
  loop:
    - hsrp
  cisco.nxos.nxos_feature:
    feature: "{{ item }}"
    state: enabled


- name: Configure HSRP at Distribution
  tags: hsrp 
  loop: "{{ hsrp_interfaces }}"
  cisco.nxos.nxos_hsrp:
    group: "{{ item.group }}"
    vip: "{{ item.vip }}"
    interface: "{{ item.interface }}"

